### PR TITLE
Add Simplified Chinese (简体中文) <zh-cn.cfg>

### LINKED ISSUE #24: Simplified Chinese (简体中文) <zh-cn.cfg>
# Localization - ![简体中文][CN] Simplified Chinese (简体中文) <zh-cn.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[zh-ch.cfg] 🗃️

### Translation

* [x] ![简体中文][CN] Simplified Chinese (简体中文) <zh-cn.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [ ] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[CN]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Chinese-flag-sm.png "简体中文"

### PR DESCRIPTION
**Pull request by ShadowSTARS616**
# Localization

* Simplified Chinese (简体中文) <zh-cn.cfg>
  * add <zh-cn-cfg>
  * closes #24 
  * thank you to @ShadowSTARS616 

> Is it right to create PR like this? Or is it unnecessary at present?

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
@ShadowSTARS616 you can continue to edit and commit changes to patch-1 and they will continue to be automatically reflected in this PR, at least until it is either merged or closed by me.

**Comment by ShadowSTARS616** [comment]
@zer0Kerbal Oh, something unexpected happened.

I need to move to the hospital to take care of my mother for a period of time, because there are too many things I can't take away my computer, which means I can't test localized text in the game.

There may be no free wireless network there, so I may not be able to follow up the progress in time.

**Comment by zer0Kerbal** [comment]
> @zer0Kerbal Oh, something unexpected happened.
> 
> I need to move to the hospital to take care of my mother for a period of time, because there are too many things I can't take away my computer, which means I can't test localized text in the game.
> 
> There may be no free wireless network there, so I may not be able to follow up the progress in time.

Family and Real Life First.

Hopefully your mother is feeling better soon.

All good. I might merge this and that way can integrate the new improvements from en-us.cfg into it.

**Comment by zer0Kerbal** [comment]
@ShadowSTARS616 hope all is going well. going to merge this in and release a new prerelease. hopefully you will be able to update the translation when you are able to.

**Review by zer0Kerbal — APPROVED** [review]
👍 thank you @ShadowSTARS616
I know it isn't done done; might need some changes and polish; but it is a fantastic start!

**Pull request merged**
